<?php
    $GMAP_API_KEY = "AIzaSyB3rIhgEx90wqPIo7LzAkloA4YK8GxwJHQ";
?>

<!DOCTYPE html>
<html>
<head>
    <title>FMFI UK</title>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
        #map {
            height: 90%;
        }
        #info {
            height: 10%;
            background-color: seashell;
            color: forestgreen;
            font-family: "Courier 10 Pitch", monospace;
            font-size: 20px;
            padding: 0.5em;
        }
    </style>
</head>
<body>
<div id="map"></div>
<script>
    function initMap() {
        var myLatlng = {lat: 48.1512219, lng: 17.0701161};

        var map = new google.maps.Map(document.getElementById('map'), {
            center: myLatlng,
            zoom: 16,
        });

        var directionsDisplay = new google.maps.DirectionsRenderer({
            preserveViewport: true,
            draggable: true,
        });
        var directionsService = new google.maps.DirectionsService();

//        var marker = new google.maps.Marker({
//            position: myLatlng,
//            map: map,
//            title: 'Click to zoom',
//        });

//        marker.addListener('click', function() {
//            map.setZoom(20);
//            map.setCenter(marker.getPosition());
//        });

        var wayMarkers = [];
        var wayPoints = [];
        var wayCoords = [];

        map.addListener('rightclick', function () {
            for (var i = 0; i < wayMarkers.length; i++) {
                wayMarkers[i].setMap(null);
            }
            wayMarkers = [];
            wayPoints = [];
            wayCoords = [];
            directionsDisplay.setMap(null);
            info.innerHTML = "";

            updateRoute();
        });

        map.addListener('click', function (e) {
            wayMarkers.push(
                new google.maps.Marker({
                    position: e.latLng,
                    map: map,
                    draggable: true,
                })
            );

            wayPoints.push(
                {
                    location: e.latLng,
                    stopover: true,
                }
            );

            wayCoords.push(e.latLng);

            updateRoute();
        });

        function updateRoute() {
            if (wayPoints.length < 2) {
                return;
            }

            var request = {
                origin: wayPoints[0].location,
                destination: wayPoints[wayPoints.length - 1].location,
                travelMode: 'WALKING',
                waypoints: wayPoints.slice(1, -1),
                optimizeWaypoints: true,
                unitSystem: google.maps.UnitSystem.METRIC,
            };

            directionsService.route(request, function(result, status) {
                if (status == 'OK') {
                    directionsDisplay.setDirections(result);
                    directionsDisplay.setMap(map);

                    var distanceService = new google.maps.DistanceMatrixService();
                    distanceService.getDistanceMatrix(
                        {
                            origins: wayCoords,
                            destinations: wayCoords,
                            travelMode: 'WALKING',
                            unitSystem: google.maps.UnitSystem.METRIC,
                        }, function (response, status) {
                            if (status == 'OK') {
                                var origins = response.originAddresses;
                                var distance = 0;

                                for (var i = 0; i < origins.length - 1; i++) {
                                    var results = response.rows[i].elements;
                                    for (var j = 0; j < results.length; j++) {
                                        if (i+1 == j) {
                                            var element = results[j];
                                            distance += element.distance.value;
                                        }
                                    }
                                }

                                var info = document.getElementById('info');
                                distance /= 100;
                                distance = Math.round(distance);
                                distance /= 10;
                                info.innerHTML = "vzdialenosť: " + distance + " km";
                            }
                        });
                }
            });
        }
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<?= $GMAP_API_KEY ?>&callback=initMap"
        async defer>
</script>
<div id="info"></div>
</body>
</html>