<?php
    $GMAP_API_KEY = "AIzaSyB3rIhgEx90wqPIo7LzAkloA4YK8GxwJHQ";
?>

<!DOCTYPE html>
<html>
<head>
    <title>FMFI UK</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
        #map {
            height: 90%;
        }
        #info #text {
            height: 7%;
            background-color: seashell;
            color: forestgreen;
            font-family: "Courier 10 Pitch", monospace;
            font-size: 20px;
            padding: 0.5em;
            float: left;
        }
        #floating-panel {
            position: absolute;
            top: 10px;
            left: 25%;
            z-index: 5;
            background-color: #fff;
            padding: 5px;
            border: 1px solid #999;
            text-align: center;
            font-family: 'Roboto','sans-serif';
            line-height: 30px;
            padding-left: 10px;
        }
        #address {
            width: 400px;
            height: 20px;
        }
        #slider {
            float: right;
            width: 300px;
            margin: 25px 15px;
        }
    </style>
</head>
<body>
<div id="floating-panel">
    <input id="address" type="textbox" value="vysoke tatry">
    <input id="submit" type="button" value="Geocode">
</div>
<div id="map"></div>
<script>
    function initMap() {
        var myLatlng = {lat: 48.1512219, lng: 17.0701161};

        var map = new google.maps.Map(document.getElementById('map'), {
            center: myLatlng,
            zoom: 16,
        });

        function geolocate() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position) {
                    var geolocation = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };

                    map.setCenter(geolocation);
                });
            }
        }

        geolocate(); // nefunguje v Chrome pre insecure locations (na https servri to pojde ???) vo FF ide ok



        var geocoder = new google.maps.Geocoder();

        document.getElementById('submit').addEventListener('click', function() {
            geocodeAddress(geocoder, map);
        });

        function geocodeAddress(geocoder, resultsMap) {
            var address = document.getElementById('address').value;
            geocoder.geocode({'address': address, 'region': 'SK'}, function(results, status) {
                if (status === 'OK') {
                    resultsMap.setCenter(results[0].geometry.location);
                } else {
                    alert('Geocode was not successful for the following reason: ' + status);
                }
            });
        }

        var autocomplete = new google.maps.places.Autocomplete(document.getElementById('address'), {});


        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////


        var directionsDisplay = new google.maps.DirectionsRenderer({
            preserveViewport: true,
            draggable: true,
        });

        var directionsService = new google.maps.DirectionsService();

        var routeStart = null;
        var routeEnd = null;

        map.addListener('click', function (e) {
            if (routeStart == null) {
                routeStart = e.latLng;
            } else if (routeEnd == null) {
                routeEnd = e.latLng;

                initRoute();
            }
        });

        var playerMarker = new google.maps.Marker({
            map: map,
        });

        var slider = document.getElementById('slider');

        var infoText = document.getElementById('text');

        function initRoute() {
            var request = {
                origin: routeStart,
                destination: routeEnd,
                travelMode: 'WALKING',
                unitSystem: google.maps.UnitSystem.METRIC,
            };

            directionsService.route(request, function(result, status) {
                if (status == 'OK') {
                    directionsDisplay.setDirections(result);
                    directionsDisplay.setMap(map);

                    updateRoute(result)
                }
            });
        }

        directionsDisplay.addListener('directions_changed', function (e) {
            var directionsResult = directionsDisplay.getDirections();

            updateRoute(directionsResult);
        });

        function updateRoute(directionsResult) {
            console.log(directionsResult);
            console.log(directionsResult.routes[0].legs[0].distance.text);
            console.log(directionsResult.routes[0].legs[0].distance.value);
            console.log(directionsResult.routes[0].overview_path);

            var steps = directionsResult.routes[0].legs[0].steps;
            var totalDistanceText = directionsResult.routes[0].legs[0].distance.text;

            var path = [steps[0].start_point];
            var distance = 0;
            var checkDistances = [0];
            var checkPoints = [0];

            for (var i = 0; i < steps.length; i++) {
                path.push(steps[i].end_point);
                var partialDistance = steps[i].distance.value;
                distance += partialDistance;
                checkDistances.push(partialDistance);
                checkPoints.push(distance);
            }



            console.log(path);
            console.log(distance);
            console.log(checkDistances);
            console.log(checkPoints);

            slider.setAttribute("max", distance);

            function setPlayerMarker(travelledDistance) {
                var ix = 0;
                while (travelledDistance > checkPoints[ix] &&
                ix < checkPoints.length - 1 &&
                travelledDistance >= checkPoints[ix + 1]) {
                    ix++
                }
                return ix;
            }

            var pos = path[setPlayerMarker(slider.value)];
            playerMarker.setPosition(pos);
            infoText.innerHTML = "celková vzdialenosť: " + totalDistanceText + "<br />" + slider.value + "m   /   " + distance + "m";

            slider.addEventListener('change', function () {
                var pos = path[setPlayerMarker(slider.value)];
                playerMarker.setPosition(pos);
                infoText.innerHTML = "celková vzdialenosť: " + totalDistanceText + "<br />" + slider.value + "m   /   " + distance + "m";
            });

            slider.addEventListener('input', function () {
                var pos = path[setPlayerMarker(slider.value)];
                playerMarker.setPosition(pos);
                infoText.innerHTML = "celková vzdialenosť: " + totalDistanceText + "<br />" + slider.value + "m   /   " + distance + "m";
            });
        }
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<?= $GMAP_API_KEY ?>&callback=initMap&language=sk&region=SK&libraries=places"
        async defer>
</script>
<div id="info">
    <div id="text"></div>
    <input type="range" id="slider" min="0" value="0">
</div>
</body>
</html>